let mascotas = [{
    'nombre': 'Doki',
    'animal': 'Perro',
    'edad': '5',
    'genero': 'Macho',
    'calificacion': '2.5'
}, {
    'nombre': 'Tasha',
    'animal': 'Perro',
    'edad': '9',
    'genero': 'Hembra',
    'calificacion': '2.5',
}, {
    'nombre': 'Cleo',
    'animal': 'Gato',
    'edad': '1',
    'genero': 'Hembra',
    'calificacion': '3'
}, {
    'nombre': 'Pancho',
    'animal': 'Conejo',
    'edad': '6',
    'genero': 'Macho',
    'calificacion': '3'
}, {
    'nombre': 'Lolita',
    'animal': 'Lora',
    'edad': '7',
    'genero': 'Hembra',
    'calificacion': '1'
}];